export const VAULT_FACTORY_ADDRESS = process.env.NEXT_PUBLIC_VAULT_FACTORY_ADDRESS || "";
export const AGENT_REGISTRY_ADDRESS = process.env.NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS || "";
export const USDC_SAC_ADDRESS = process.env.NEXT_PUBLIC_USDC_SAC_ADDRESS || "";
export const DEMO_VAULT_ADDRESS = "CBIT2CL7N32AXFS66S3E5J3O3E33GIBSS4UX3VCOHB7YZKDLDHU52RKR";

// Agent signer public key for the demo
export const AGENT_SIGNER_PUBLIC_KEY = "GBJCC5E3IK7EI6PAVQ5LZ2L3CU2G4EKGJBULIM776LS5DBVPVHXBQBYE";

// Facilitator public key (receives x402 payments on behalf of service)
export const FACILITATOR_PUBLIC_KEY = "GB4WBZZRI3RWJI7IUBOMO4R7SILFN2IWNXRWTLIGM7E7ZF3YV6N5HNME";
