export const VAULT_FACTORY_ADDRESS = process.env.NEXT_PUBLIC_VAULT_FACTORY_ADDRESS || "";
export const AGENT_REGISTRY_ADDRESS = process.env.NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS || "";
export const REPUTATION_REGISTRY_ADDRESS = process.env.NEXT_PUBLIC_REPUTATION_REGISTRY_ADDRESS || "";
export const VALIDATION_REGISTRY_ADDRESS = process.env.NEXT_PUBLIC_VALIDATION_REGISTRY_ADDRESS || "";
export const USDC_SAC_ADDRESS = process.env.NEXT_PUBLIC_USDC_SAC_ADDRESS || "";
export const DEMO_VAULT_ADDRESS = "CBIT2CL7N32AXFS66S3E5J3O3E33GIBSS4UX3VCOHB7YZKDLDHU52RKR";

// Agent signer public key for the demo
export const AGENT_SIGNER_PUBLIC_KEY = "GCULCDARDBS5OV5XLP2APEVZVJMQ6SP6L6EA3AEQ4NOBI2TYJBU64YNI";

// Facilitator public key (receives x402 payments on behalf of service)
export const FACILITATOR_PUBLIC_KEY = "GB4WBZZRI3RWJI7IUBOMO4R7SILFN2IWNXRWTLIGM7E7ZF3YV6N5HNME";
